//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProView.Properties
{
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "5.0.0.4696")]
	internal sealed partial class ImageViewer : global::System.Configuration.ApplicationSettingsBase
	{
		
		private static ImageViewer defaultInstance = ((ImageViewer)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ImageViewer())));
		
		public static ImageViewer Default
		{
			get
			{
				return defaultInstance;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("96")]
		public int PDFResolution
		{
			get
			{
				return ((int)(this["PDFResolution"]));
			}
			set
			{
				this["PDFResolution"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string ZoomQuality
		{
			get
			{
				return ((string)(this["ZoomQuality"]));
			}
			set
			{
				this["ZoomQuality"] = value;
			}
		}
	}
}
