//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProView.Properties
{
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "5.0.0.4696")]
	internal sealed partial class MainForm : global::System.Configuration.ApplicationSettingsBase
	{
		
		private static MainForm defaultInstance = ((MainForm)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MainForm())));
		
		public static MainForm Default
		{
			get
			{
				return defaultInstance;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0.5")]
		public double SplitterDistance
		{
			get
			{
				return ((double)(this["SplitterDistance"]));
			}
			set
			{
				this["SplitterDistance"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int SplitterOrientation
		{
			get
			{
				return ((int)(this["SplitterOrientation"]));
			}
			set
			{
				this["SplitterOrientation"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
		public global::System.Drawing.Point WindowPosition
		{
			get
			{
				return ((global::System.Drawing.Point)(this["WindowPosition"]));
			}
			set
			{
				this["WindowPosition"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("1024, 768")]
		public global::System.Drawing.Size WindowSize
		{
			get
			{
				return ((global::System.Drawing.Size)(this["WindowSize"]));
			}
			set
			{
				this["WindowSize"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("2")]
		public int WindowState
		{
			get
			{
				return ((int)(this["WindowState"]));
			}
			set
			{
				this["WindowState"] = value;
			}
		}
	}
}
